spring:
  application:
    name: 331-backend

  # DO NOT hardcode active profiles here; set via SPRING_PROFILES_ACTIVE env.
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:finalprojectdb}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

supabase:
  storage:
    endpoint: ${SUPABASE_ENDPOINT:https://example.storage.supabase.co/storage/v1/s3}
    endpoint_output: ${SUPABASE_PUBLIC_ENDPOINT:https://example.storage.supabase.co/storage/v1/object/public}
    bucket: ${SUPABASE_BUCKET:profileimage}
    region: ${SUPABASE_REGION:ap-southeast-1}
    accessKey: ${SUPABASE_ACCESS_KEY:changeme}
    secretKey: ${SUPABASE_SECRET_KEY:changeme}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:changeme}
      expiration: ${JWT_EXPIRATION_MS:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}
