services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
    # Removed healthcheck

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - db

  backend:
    image: ${DOCKER_HUB_USERNAME}/se331-backend:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8999:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/finalprojectdb
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
    # Removed healthcheck

  frontend:
    image: ${DOCKER_HUB_USERNAME}/se331-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8001:80"
    environment:
      VITE_BACKEND_BASE: "http://backend:8999/api/v1"

volumes:
  dbdata:
