services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9090:80"
    depends_on: [db]

  backend:
    image: ${DOCKER_HUB_USERNAME}/se331-backend:latest
    restart: unless-stopped
    depends_on: [db]
    ports:
      - "8999:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_ENDPOINT: ${SUPABASE_ENDPOINT}
      SUPABASE_PUBLIC_ENDPOINT: ${SUPABASE_PUBLIC_ENDPOINT}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      SUPABASE_REGION: ${SUPABASE_REGION}
      SUPABASE_ACCESS_KEY: ${SUPABASE_ACCESS_KEY}
      SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY}

  frontend:
    image: ${DOCKER_HUB_USERNAME}/se331-frontend:latest
    restart: unless-stopped
    depends_on: [backend]
    ports:
      - "8001:80"

volumes:
  dbdata:
