services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - db

  backend:
    image: ${DOCKER_HUB_USERNAME}/se331-backend:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy  
    ports:
      - "8999:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/finalprojectdb  
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}  
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}  
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: Bearer ${JWT_SECRET}", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  frontend:
    image: ${DOCKER_HUB_USERNAME}/se331-frontend:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy  
    ports:
      - "8001:80"
    environment:
      VITE_BACKEND_BASE: "http://backend:8999/api/v1"

volumes:
  dbdata:
